### ISSUE TITLE
Bug #2 incorrect "chmod" command in setup.sh caused system failure

### ISSUE THREAD

**Issue by conquistador1492** [FOPF/pathmaker#1]
Traceback (most recent call last):
  File "/usr/lib/cgi-bin/path.py", line 71, in <module>
    main()
  File "/usr/lib/cgi-bin/path.py", line 68, in main
    print_html()
  File "/usr/lib/cgi-bin/path.py", line 55, in print_html
    path = PathMap(PATH_TO_SVG + BASE_SVG_NAME)
  File "/usr/lib/cgi-bin/pathMap.py", line 32, in **init**
    doc = etree.parse(in_file_svg)
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:85131)
  File "src/lxml/parser.pxi", line 1782, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:124005)
  File "src/lxml/parser.pxi", line 1808, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:124374)
  File "src/lxml/parser.pxi", line 1712, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:123169)
  File "src/lxml/parser.pxi", line 1115, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:117533)
  File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:110510)
  File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:112276)
  File "src/lxml/parser.pxi", line 611, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:111078)
OSError: Error reading file '/var/www/html/drawing.svg': failed to load external entity "/var/www/html/drawing.svg"

**Comment by smnnk** [comment]
Fixed.
